"""Add Phase 1 CRM Models

Revision ID: db20e00f5c2e
Revises: b08c9eed2874
Create Date: 2026-09-03 12:55:53.743469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db20e00f5c2e'
down_revision: Union[str, None] = 'b08c9eed2874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('requirement_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_inquiries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.add_column('requirements', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('requirements', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('requirements', sa.Column('customer_phone', sa.String(length=50), nullable=True))
    op.add_column('requirements', sa.Column('customer_whatsapp', sa.String(length=50), nullable=True))
    op.add_column('requirements', sa.Column('property_status', sa.String(length=100), nullable=True))
    op.add_column('requirements', sa.Column('location_city', sa.String(length=100), nullable=True))
    op.add_column('requirements', sa.Column('location_state', sa.String(length=100), nullable=True))
    op.add_column('requirements', sa.Column('location_locality', sa.String(length=255), nullable=True))
    op.add_column('requirements', sa.Column('scope', sa.String(length=255), nullable=True))
    op.add_column('requirements', sa.Column('property_size', sa.String(length=100), nullable=True))
    op.add_column('requirements', sa.Column('budget_range', sa.String(length=100), nullable=True))
    op.add_column('requirements', sa.Column('timeline', sa.String(length=100), nullable=True))
    op.add_column('requirements', sa.Column('design_preferences', sa.Text(), nullable=True))
    op.add_column('requirements', sa.Column('additional_notes', sa.Text(), nullable=True))
    op.alter_column('requirements', 'property_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('requirements', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('requirements', 'expected_start_date')
    op.drop_column('requirements', 'expected_end_date')
    op.drop_column('requirements', 'service_type')
    op.drop_column('requirements', 'budget_max')
    op.drop_column('requirements', 'budget_min')
    op.drop_column('requirements', 'buildup_area')
    op.drop_column('requirements', 'num_rooms')
    op.drop_column('requirements', 'carpet_area')
    op.drop_column('requirements', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('city', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('requirements', sa.Column('carpet_area', mysql.FLOAT(), nullable=True))
    op.add_column('requirements', sa.Column('num_rooms', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('requirements', sa.Column('buildup_area', mysql.FLOAT(), nullable=True))
    op.add_column('requirements', sa.Column('budget_min', mysql.FLOAT(), nullable=True))
    op.add_column('requirements', sa.Column('budget_max', mysql.FLOAT(), nullable=True))
    op.add_column('requirements', sa.Column('service_type', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('requirements', sa.Column('expected_end_date', mysql.DATETIME(), nullable=True))
    op.add_column('requirements', sa.Column('expected_start_date', mysql.DATETIME(), nullable=True))
    op.alter_column('requirements', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('requirements', 'property_type',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('requirements', 'additional_notes')
    op.drop_column('requirements', 'design_preferences')
    op.drop_column('requirements', 'timeline')
    op.drop_column('requirements', 'budget_range')
    op.drop_column('requirements', 'property_size')
    op.drop_column('requirements', 'scope')
    op.drop_column('requirements', 'location_locality')
    op.drop_column('requirements', 'location_state')
    op.drop_column('requirements', 'location_city')
    op.drop_column('requirements', 'property_status')
    op.drop_column('requirements', 'customer_whatsapp')
    op.drop_column('requirements', 'customer_phone')
    op.drop_column('requirements', 'customer_email')
    op.drop_column('requirements', 'customer_name')
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    op.drop_table('contact_inquiries')
    op.drop_table('consultation_requests')
    # ### end Alembic commands ###
