"""Rename s3_key to file_path in documents

Revision ID: a9447ab11fe9
Revises: 2bb62df2bb3f
Create Date: 2026-09-01 15:50:44.801776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9447ab11fe9'
down_revision: Union[str, None] = '2bb62df2bb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.drop_column('documents', 's3_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('s3_key', mysql.VARCHAR(length=500), nullable=False))
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
