"""Add is_featured to products

Revision ID: fca192e02ac5
Revises: db20e00f5c2e
Create Date: 2026-09-03 17:03:58.179068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca192e02ac5'
down_revision: Union[str, None] = 'db20e00f5c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_featured')
    # ### end Alembic commands ###
